### ISSUE TITLE
Need an Intercative ReadMe

### ISSUE THREAD

**Issue by stephin007** [stephin007/githubfinder#10]
Whosoever is reading this, Need a creative Readme for this repo which includes badges, descriptive images etc.
pitch in your idea.
If you wanna check the project, it's live on the URL given below the about section

**Comment by ameybhavsar24** [comment]
@stephin007 
Badges seem already fine.
Adding cloning, installation and usage instructions specific to this project might be helpful to a novice. Contributing section could be added.
Other than that, maybe a simple GIF could be added showing how to use the live app.
If that works with you, please assign it to me.

**Comment by stephin007** [comment]
That's an awesome suggestion... @ameybhavsar24 Please go ahead....and revert back asap.

Also, leave a star ⭐ if you like the project.

**Comment by stephin007** [comment]
@ameybhavsar24 
Few points to note:

1. Don't clone directly from my repo.
2. Fork my repo and then clone it
3. Create a branch, whose naming convention must be: (username)/testcase/(fileName)
You should create a different branch for test cases in different files.

Rest if you still have any queries, please mailme at : mail@stephinreji.me, if i dont respond here

**Comment by ameybhavsar24** [comment]
Noted.
Can you assign this explicitly so that it's easy for me to search back here?

**Comment by stephin007** [comment]
Done @ameybhavsar24 ...please continue with your work

**Comment by stephin007** [comment]
@ameybhavsar24 any progress?

**Comment by ameybhavsar24** [comment]
Yes, I'll make a PR by today evening. IST time.

**Comment by stephin007** [comment]
Okay @ameybhavsar24 💯

**Comment by Justinnn07** [comment]
me karu 🤣😂..
may i?

**Comment by stephin007** [comment]
Its Already assigned! @Justinnn07 :) ... you can check some other issues I mentioned i.e.

https://github.com/stephin007/WeatherMan/issues/7
